const DB_NAME = "Backend_WorkFlow";

const CLOUDINARY_CLOUD_NAME = String(process.env.CLOUDINARY_CLOUD_NAME);
const CLOUDINARY_API_KEY = String(process.env.CLOUDINARY_API_KEY);
const CLOUDINARY_API_SECRET = String(process.env.CLOUDINARY_API_SECRET);

export {
    DB_NAME,
    CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET,
};
